image: alpine/edge
packages:
  - curl-dev
  - gtk+3.0-dev
  - meson
  - json-glib-dev
  - libhandy-dev
  # annotatec deps
  - flex
  - bison
secrets:
  - 94676d1a-b869-45ae-a799-ea60c0eea985
sources:
  - https://git.sr.ht/~tristan957/harvest-almanac
  - https://git.sr.ht/~sircmpwn/annotatec
tasks:
  - setup: |
      cd harvest-almanac
      CC=gcc meson -Dwerror=true -Dbuildtype=release build
  - build: |
      cd harvest-almanac
      ninja -C build
  - annotatec: |
      cd annotatec
      make
      sudo make install PREFIX=/usr
  - annotate: |
      cd harvest-almanac
      find . -name "*.c" | xargs \
        annotatec -gC "cpp -std=gnu11 -U __GNUC__ -D HANDY_USE_UNSTABLE_API -Ilib \
          $(pkg-config --cflags gio-2.0 json-glib-1.0 gtk+-3.0 libhandy-0.0 \
          libcurl)" > annotations.json
      ~/upload-annotations annotations.json tristan957 harvest-almanac
