image: alpine/edge
packages:
  - gtk+3.0-dev
  - meson
  - json-glib-dev
  - libhandy-dev
  - libsoup-dev
  - libsecret-dev
  - flatpak-builder
secrets:
  - 92357bf7-1b44-4630-999e-fca4a120c50b
  - 2fc824d8-76d2-4052-a53b-984639bed2a1
sources:
  - https://git.sr.ht/~tristan957/harvest-almanac
tasks:
  - setup: |
      cd harvest-almanac
      CC=gcc meson -Dwerror=true -Dbuildtype=release -Dwarning_level=2 build
  - build: |
      cd harvest-almanac
      ninja -C build
  # - flatpak: |
  #     cd harvest-almanac
  #     flatpak-builder --verbose --sandbox --force-clean --repo=.flatpak-repo \
  #       --ccache --user --install-deps-from=flathub --install .flatpak \
  #       dist/flatpak/io.partin.tristan.HarvestAlmanac.yaml
  - test: |
      cd harvest-almanac
      . ~/.harvest-almanac.env
      ninja test -C build
