image: alpine/edge
packages:
  - gtk+3.0-dev
  - meson
  - json-glib-dev
  - libhandy-dev
  - libsoup-dev
  - libsecret-dev
secrets:
  - 92357bf7-1b44-4630-999e-fca4a120c50b
sources:
  - https://git.sr.ht/~tristan957/harvest-almanac
tasks:
  - setup: |
      cd harvest-almanac
      CC=gcc meson -Dwarning_level=3 -Dbuildtype=release build
  - build: |
      cd harvest-almanac
      ninja -C build
