image: fedora/latest
packages:
  - gcc
  - libcurl-devel
  - gtk3-devel
  - meson
  - json-glib-devel
  - make
  - git
  - gobject-introspection # libhandy
sources:
  - https://git.sr.ht/~tristan957/harvest-almanac
tasks:
  - setup: |
      cd harvest-almanac
      CC=gcc meson -Dwerror=true -Dbuildtype=release -Dlibhandy:glade_catalog=disabled build
  - build: |
      cd harvest-almanac
      ninja -C build
